name = "Quaternionic"
uuid = "0756cd96-85bf-4b6f-a009-b5012ea7a443"
authors = ["Michael Boyle <michael.oliver.boyle@gmail.com>"]
version = "1.5.1"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ChainRulesCore = "1"
FastDifferentiation = "0.3.14"
ForwardDiff = "0.10"
GenericLinearAlgebra = "0.3.11"
LaTeXStrings = "1"
Latexify = "0.15, 0.16"
LinearAlgebra = "1"
PrecompileTools = "1.1.1"
Random = "1"
Requires = "1"
StaticArrays = "1"
Symbolics = "0.1, 1, 2, 3, 4, 5"
julia = "1.6"

[extensions]
QuaternionicChainRulesCoreExt = "ChainRulesCore"
QuaternionicFastDifferentiationExt = "FastDifferentiation"
QuaternionicForwardDiffExt = "ForwardDiff"
QuaternionicSymbolicsExt = "Symbolics"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
